### ISSUE TITLE
empty json* files

### ISSUE THREAD

**Issue by delphir-com** [NightRang3r/Broadlink-e-control-db-dump#32]
for some reason all of the json* files needed for NON-ROOT method are just 2byte files containing `[]` characters inside for me.

I tried "sharing" multiple times, but there is no difference. 
Any idea what else can I try to solve this?

**Comment by vasi26ro** [comment]
I have the same problem. I can't get the codes.

**Comment by delphir-com** [comment]
> I have the same problem. I can't get the codes.

for me the solution was to ignore this method at all and configure SP3 switch directly in configuration.yaml (no extra installations required) like this (make sure to replace the IP(host) and MAC with the actual values of your SP3 device:

```
switch:
  - platform: broadlink
    host: 192.168.1.100
    mac: 'XX:XX:XX:XX:XX:XX'
    timeout: 3
    type: sp3

```
